version: '3'
services:
  dockerps-web:
    image: golang
    container_name: dockerps-web
    entrypoint: /bin/bash -c "cd /host && go build -o dockerps-web && ./dockerps-web"
    environment:
      - PORT=80
    ports:
      - 80:80
    volumes:
      - ./:/host
      - /var/run/docker.sock:/var/run/docker.sock
